language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

before_cache:
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew build -s
  - rm -f build/libs/*-*dev.jar build/libs/*-sources*.jar
