language: java
if: tag IS present

# skips
install: true

git:
  depth: 1

jdk: oraclejdk11

script: ./gradlew --no-daemon build -s

before_cache:
  - find $HOME/.gradle/ -name "*.lock" -type f -delete
  - find $HOME/.gradle/ -name "cache.properties" -type f -delete
  - find $HOME/.gradle/ -name "file-access.bin" -type f -delete

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/


before_deploy:
  - mv ./build/libs/mc-autotool-0.0.1.jar ./build/libs/autotool.jar
  - rm -f ./build/libs/*-*.jar


deploy:
  provider: releases
  overwrite: true
  api_key: "$GH_TOKEN"
  target_commitish: $TRAVIS_COMMIT
  name: For minecraft $TRAVIS_BRANCH
  body: So this is it, huh?
  file_glob: true
  file: ./build/libs/autotool.jar
  on:
    tags: true
  skip_cleanup: true
  draft: false
  prerelease: false
  force_update: true
